Added check for job validate logfile

diff --git a/.github/workflows/casper-a100.yml b/.github/workflows/casper-a100.yml
--- a/.github/workflows/casper-a100.yml
+++ b/.github/workflows/casper-a100.yml
@@ -57,7 +57,13 @@ jobs:
 
       - name: Verify run
         run: |
-          if [ $? -ne 0 ]; then
-            echo "Run failed"
+          if [ ! -f validate/validate_job.log ]; then
+            echo "Run failed: validate_job.log not found"
             exit 1
           fi
+          if [ $(grep -c "Hello World" validate/validate_job.log) -ne 2 ]; then
+            echo "Run failed: validate_job.log does not contain 'Hello World' in both lines"
+            exit 1
+          fi
+          cat validate/validate_job.log
+          if 
