updated yaml

diff --git a/.github/workflows/casper-a100-label.yml b/.github/workflows/casper-a100-label.yml
--- a/.github/workflows/casper-a100-label.yml
+++ b/.github/workflows/casper-a100-label.yml
@@ -5,66 +5,74 @@ on:
     types:
       - labeled
 
+# Workflow global variables
+env:
+  WORKFLOW_REPO: neumanbrett/cuda_ghactions_basic
+  WORKFLOW_RUNNER: basic-runner
+
 jobs:
   
   build-and-run:
-    runs-on: basic-runner
-    if: |
-      github.event.label.name == 'casper-a100' &&
-      github.repository == 'neumanbrett/cuda_ghactions_basic'
 
+    # Environment variables per job
     env:
-      USER: bneuman
-      PBS_ACCOUNT: SCSG0001
+      # Github workflow variables
+      WORKFLOW_LABEL: casper-a100
+
+      # NCAR / System variables
+      WORKFLOW_PBS_JOBSCRIPT: validate/run-validate.pbs
+      WORKFLOW_USER: bneuman
+      WORKFLOW_PBS_ACCOUNT: SCSG0001
+      # Path to script that will load correct modules for the code
+      WORKFLOW_MODULES: config/config.modules
+      WORKFLOW_RUN_LOG: $SCRATCH/tmp/validation_job.log.$(date +"%d-%m-%Y")
+
+    runs-on: ${{ env.WORKFLOW_RUNNER }}
+    if: |
+      github.event.label.name == ${{ env.WORKFLOW_LABEL }} &&
+      github.repository == ${{ env.WORKFLOW_REPO }}
 
     steps:
       - name: Check out the repository code
         uses: actions/checkout@v3
 
-      - name: Source system variables based on label
-        run: |
-          source config/config.modules
-          source config/config.pbs
-
       - name: Run make
-        run: make > make.log 2>&1
-          
-      - name: Verify compilation
-        run: |
-          if [ ! -f bin/hello_world ]; then
-            echo "Compilation failed: binary not found"
-            exit 1
-          fi
-          if [ ! -s make.log ]; then
-            echo "Compilation failed: make.log is empty"
-            exit 1
-          fi
-          if ! tail -n 1 make.log | grep -q "Success"; then
-            echo "Compilation failed: make.log does not end with 'Success'"
-            exit 1
-          fi
-          cat make.log > $SCRATCH/tmp/make.log.$(date +"%d-%m-%Y")
-          rm make.log
+        run: make
 
-      - name: Submit PBS job to run executable
-        #run: JOBID = $(qsub -A $PBS_ACCOUNT -l select=1:ncpus=1:ngpus=1:mem=10GB:gpu_model=a100 -l walltime=00:05:00 -N hello_world -o hello_world.out -e hello_world.err bin/hello_world)
-        run: |
-          echo $USER
-          qsub -Wblock=true validate/run-validate.pbs
+      # - name: Verify compilation
+      #   run: |
+      #     if [ ! -f bin/hello_world ]; then
+      #       echo "Compilation failed: binary not found"
+      #       exit 1
+      #     fi
+      #     if [ ! -s make.log ]; then
+      #       echo "Compilation failed: make.log is empty"
+      #       exit 1
+      #     fi
+      #     if ! tail -n 1 make.log | grep -q "Success"; then
+      #       echo "Compilation failed: make.log does not end with 'Success'"
+      #       exit 1
+      #     fi
+      #     cat make.log > $SCRATCH/tmp/make.log.$(date +"%d-%m-%Y")
+      #     rm make.log
 
-      - name: Verify run
+      - name: Submit PBS job and run tests
         run: |
-          if [ ! -f validate/validate_job.log ]; then
-            echo "Run failed: validate_job.log not found"
-            exit 1
-          fi
-          if ! grep -q "CPU" validate/validate_job.log; then
-            echo "The job did not run on the CPU"
-            exit 1
-          fi
-          if ! grep -q "GPU" validate/validate_job.log; then
-            echo "The job did not run on the GPU"
-            exit 1
-          fi
-          cat validate/validate_job.log > $SCRATCH/tmp/validate_job.log.$(date +"%d-%m-%Y") 
-          rm validate/validate_job.log 
+          qsub -Wblock=true ${{ env.WORKFLOW_PBS_JOBSCRIPT }}
+
+      # - name: Verify run
+      #   run: |
+      #     if [ ! -f validate/validate_job.log ]; then
+      #       echo "Run failed: validate_job.log not found"
+      #       exit 1
+      #     fi
+      #     if ! grep -q "CPU" validate/validate_job.log; then
+      #       echo "The job did not run on the CPU"
+      #       exit 1
+      #     fi
+      #     if ! grep -q "GPU" validate/validate_job.log; then
+      #       echo "The job did not run on the GPU"
+      #       exit 1
+      #     fi
+      #     cat validate/validate_job.log > $SCRATCH/tmp/validate_job.log.$(date +"%d-%m-%Y") 
+      #     rm validate/validate_job.log 
