Updated workflow with compile and run validations

diff --git a/.github/workflows/casper-a100.yml b/.github/workflows/casper-a100.yml
--- a/.github/workflows/casper-a100.yml
+++ b/.github/workflows/casper-a100.yml
@@ -1,18 +1,18 @@
 name: casper-a100
 run-name: ${{ github.actor }} compiling and running CUDA hello world example
 on:
+  push:
+    branches:
+      - main
   pull_request:
-    types:
-      - labeled
+    branches:
+      - main
 
 jobs:
   
   build-and-run:
-    runs-on: hpc-runner
-    if: |
-      github.event.label.name == 'casper-a100' &&
-      github.repository == 'neumanbrett/fasteddy_cicd'
-
+    runs-on: basic-runner
+  
     env:
       USER: bneuman
       PBS_ACCOUNT: SCSG0001
@@ -22,25 +22,32 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Source system variables based on label
-        if: github.event.label.name == 'casper-a100'
         run: |
-          echo ""
+          source config/config.modules
+          source config/config.pbs
 
       - name: Run make
-        run: make
-
+        run: make > make.log 2>&1
+          
       - name: Verify compilation
         run: |
-          if [ ! -f path/to/compiled/binary ]; then
+          if [ ! -f bin/hello_world ]; then
             echo "Compilation failed: binary not found"
             exit 1
           fi
+          if [ ! -s make.log ]; then
+            echo "Compilation failed: make.log is empty"
+            exit 1
+          fi
+          if ! tail -n 1 make.log | grep -q "Success"; then
+            echo "Compilation failed: make.log does not end with 'Success'"
+            exit 1
+          fi
+          rm make.log
 
-      - name: Run test
-        run: make check
-
-      - name: Run the binary
-        run: path/to/compiled/binary
+      - name: Submit PBS job to run executable
+        #run: JOBID = $(qsub -A $PBS_ACCOUNT -l select=1:ncpus=1:ngpus=1:mem=10GB:gpu_model=a100 -l walltime=00:05:00 -N hello_world -o hello_world.out -e hello_world.err bin/hello_world)
+        run: qsub validate/run-validate.pbs
 
       - name: Verify run
         run: |
